import Head from "next/head";
import Landing from "../components/Landing";
import styles from "../styles/index.module.scss";
import Bar from "../components/Bar";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Rhamsez Thevenin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Bar />
        <Landing>
          {/* <div className={styles.content}>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
            <p>Example Content</p>
          </div> */}
        </Landing>
      </main>
    </div>
  );
}
