import Head from "next/head";
import Landing from "../components/Landing";
import styles from "../styles/index.module.scss";
import Bar from "../components/Bar";
import Panel from "../components/Panel";

import portrait from "../public/portrait.jpg";
import idi from "../public/idi.png";

export default function Index() {
  const about_me = {
    title: "About Me",
    content: [
      {
        image: portrait.src,
        subtitle: "Hi, I'm Rhamsez!",
        paragraph: `As of 1/2/2023, 
        I am 3rd year Software Engineer Major in RIT. 
        Currently, 
        I'm a Software Engineer for Midnight Mansion, 
        but I will soon become an intern for IDI Billings this January.`,
      },
    ],
  };
  const experience = {
    title: "Experience",
    content: [
      {
        image: idi.src,
        subtitle: "Software Engineer Intern at IDI Billings",
        paragraph: `From January 2023 to August 2023,
        I will be an intern for IDI Billings. 
        A description of my accomplishments and responsibilities will be provided in the future.`,
      },
      {
        image: idi.src,
        subtitle: "Software Engineer at Midnight Mansion",
        paragraph: `Since September 2022,
        I have been a Software Engineer for Midnight Mansion.
        I have created/managed websites for MIT classes, as well as
        build launch and intranet websites for the respected startup.`,
      },
    ],
  };
  const projects = {};
  const contact = {};

  return (
    <div className="indexContainer">
      <Head>
        <title>Rhamsez Thevenin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rozefavicon.ico" />
      </Head>
      <main>
        <Bar />
        <Landing>
          <div className={styles.content}>
            <Panel id="about_me" content={about_me} />
            <Panel id="experience" type="dark" content={experience} />
            {/* <Panel id="projects" />
            <Panel id="contact" type="dark" /> */}
          </div>
        </Landing>
      </main>
    </div>
  );
}
